### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by vramdal** [nrkno/MMM-Slack#1]
When setting up the module:
```
{
    module: 'MMM-Slack',
    position: 'lower_third',
    config: {
        slackToken: '<token here>',
        slackChannel: 'mm'
    }
}
```

When posting a message to the `mm` channel, the following stacktrace is produced:

```
TypeError: Cannot read property 'id' of undefined
    at RTMClient.<anonymous> (/Users/vramdal/dev/MagicMirror/modules/MMM-Slack/node_helper.js:38:39)
    at RTMClient.emit (/Users/vramdal/dev/MagicMirror/node_modules/eventemitter3/index.js:115:35)
    at RTMClient.emit (/Users/vramdal/dev/MagicMirror/node_modules/@slack/client/lib/clients/client.js:79:39)
    at RTMClient._handleHello (/Users/vramdal/dev/MagicMirror/node_modules/@slack/client/lib/clients/rtm/client.js:621:8)
    at RTMClient._handleWsMessageInternal (/Users/vramdal/dev/MagicMirror/node_modules/@slack/client/lib/clients/rtm/client.js:435:10)
    at RTMClient.handleWsMessage (/Users/vramdal/dev/MagicMirror/node_modules/@slack/client/lib/clients/rtm/client.js:417:10)
    at WebSocket.wrapper (/Users/vramdal/dev/MagicMirror/node_modules/@slack/client/node_modules/lodash/lodash.js:4968:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/vramdal/dev/MagicMirror/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/vramdal/dev/MagicMirror/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/vramdal/dev/MagicMirror/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/vramdal/dev/MagicMirror/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/vramdal/dev/MagicMirror/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/Users/vramdal/dev/MagicMirror/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/Users/vramdal/dev/MagicMirror/node_modules/ws/lib/Receiver.js:499:31)
```

**Comment by pic0frame** [comment]
I have the same issue when starting magic mirror with the mmm-slack module active.

**Comment by ottopaulsen** [comment]
I had the same issue, and found the reason. The slack channel must be private for this to work. If it is public, it will not be found by the getGroupByName function called in node_helper.js row 35.

**Comment by sitr** [comment]
That's correct. When I developed this module, it was first considered for internal use and I restricted it to private channels only. I'll will make a fix for this.
